package trigger

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/pgbkrs/pgbackup/internal/core"
)

// Compile-time interface check.
var _ core.SchemaFetcher = (*SchemaFetcher)(nil)

// tgtype bitmask constants from PostgreSQL include/catalog/pg_trigger.h.
const (
	tgTypeBefore    = 0x02 // BEFORE timing
	tgTypeInsert    = 0x04 // INSERT event
	tgTypeDelete    = 0x08 // DELETE event
	tgTypeUpdate    = 0x10 // UPDATE event
	tgTypeTruncate  = 0x20 // TRUNCATE event
	tgTypeInsteadOf = 0x40 // INSTEAD OF timing
)

// decodeTiming maps the tgtype bitmask to a timing string.
// INSTEAD OF takes precedence over BEFORE; if neither bit is set, timing is AFTER.
func decodeTiming(tgtype int) string {
	if tgtype&tgTypeInsteadOf != 0 {
		return "INSTEAD OF"
	}
	if tgtype&tgTypeBefore != 0 {
		return "BEFORE"
	}
	return "AFTER"
}

// decodeEvents maps the tgtype bitmask to an ordered slice of event strings.
// Order: INSERT, UPDATE, DELETE, TRUNCATE — deterministic regardless of bit set order.
func decodeEvents(tgtype int) []string {
	var events []string
	if tgtype&tgTypeInsert != 0 {
		events = append(events, "INSERT")
	}
	if tgtype&tgTypeUpdate != 0 {
		events = append(events, "UPDATE")
	}
	if tgtype&tgTypeDelete != 0 {
		events = append(events, "DELETE")
	}
	if tgtype&tgTypeTruncate != 0 {
		events = append(events, "TRUNCATE")
	}
	return events
}

// SchemaFetcher fetches trigger definitions from pg_catalog.
// Only user-defined triggers (tgisinternal=false) are returned.
type SchemaFetcher struct{}

const fetchQuery = `
SELECT
    t.tgname AS name,
    t.tgtype::int AS tgtype,
    c.relname AS table_name,
    p.proname AS function_name
FROM pg_trigger t
JOIN pg_class c ON c.oid = t.tgrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_proc p ON p.oid = t.tgfoid
WHERE n.nspname = $1
  AND NOT t.tgisinternal
ORDER BY c.relname, t.tgname
`

// Fetch returns TriggerDef objects for all user-defined triggers in the given schema.
// Internal triggers (tgisinternal=true) generated by constraint enforcement are excluded.
func (f *SchemaFetcher) Fetch(ctx context.Context, conn *pgx.Conn, schema string) ([]core.ObjectDef, error) {
	rows, err := conn.Query(ctx, fetchQuery, schema)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var defs []core.ObjectDef
	for rows.Next() {
		var (
			name         string
			tgtype       int
			tableName    string
			functionName string
		)
		if err := rows.Scan(&name, &tgtype, &tableName, &functionName); err != nil {
			return nil, err
		}
		defs = append(defs, core.TriggerDef{
			ObjectHeader: core.ObjectHeader{
				Kind:   core.KindTrigger,
				Schema: schema,
				Name:   name,
			},
			Timing:       decodeTiming(tgtype),
			Events:       decodeEvents(tgtype),
			TableName:    tableName,
			FunctionName: functionName,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return defs, nil
}
